name: Bug report
description: Create a bug report to help us improve. Use this template if you encountered an issue while integrating with or implementing the APIs of this SDK.
labels: [bug, triage-required]

body:
- type: checkboxes
  attributes:
    label:  Prerequisites
    description: Please check the following items before logging a new bug report.
    options:
    - label: This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk_flutter/security/policy).
      required: true
    - label: I have searched in this repository's issues to see if it has already been reported.
      required: true
    - label: I have updated to the latest released version of the SDK and the issue still persists.
      required: true

- type: textarea
  attributes:
    label: Bug summary
    description: Please provide a summary of the bug you are reporting.
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide the Platform, OS version, SDK version(s) used, IDE version, and any other specific settings that could help us narrow down the problem.
      Run `flutter doctor` and paste the output here.
      Example:
        [✓] MOBILE SDK VERSION: Flutter_aepcore@4.0.0, Flutter_aepedge@4.0.0
        [✓] Flutter (Channel stable, 3.19.6, on macOS 14.2.1 darwin-arm64)
        • Flutter version 3.19.6 on channel stable at /development/flutter
        • Dart version 3.3.4
        • DevTools version 2.31.1
        [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
        [✓] Xcode - develop for iOS and macOS (Xcode 15.1)
         • CocoaPods version 1.14.3

  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior consistently.
    placeholder: |
      1. ...
      2. ...
      3. ...
  validations:
    required: false

- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you are experiencing.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Here you can include sample code that illustrates the problem, logs taken while reproducing the problem, or anything that can give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
