//
// Created by mobile analytics on 4/26/22.
//

#ifndef AEPSDK_FLUTTER_FLUTTERAEPEDGEDATABRIDGE_H
#define AEPSDK_FLUTTER_FLUTTERAEPEDGEDATABRIDGE_H



class FlutterAEPEdgeDataBridge {

};



#endif //AEPSDK_FLUTTER_FLUTTERAEPEDGEDATABRIDGE_H
